### ISSUE TITLE
按照部署步骤之后无法正常运行

### ISSUE THREAD

**Issue by zzyss-marker** [AmiyaBot/Amiya-Bot#102]
![图片](https://user-images.githubusercontent.com/65355156/172307135-d86687dd-f800-40ca-b0d3-012d97339a90.png)

**Comment by zzyss-marker** [comment]
> ![图片](https://user-images.githubusercontent.com/65355156/172307135-d86687dd-f800-40ca-b0d3-012d97339a90.png)

**Comment by Initial-heart-1** [comment]
不要尝试随意改变 issue 状态。每次变动都会发送一封 Email 给打开 Watch 的人。

**Comment by zzyss-marker** [comment]
如何删除issue


&nbsp;


2717840744
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月12日(星期天) 中午1:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [AmiyaBot/Amiya-Bot] 按照部署步骤之后无法正常运行 (Issue #102)





 
不要尝试随意改变 issue 状态。每次变动都会发送一封 Email 给打开 Watch 的人。

**Comment by Initial-heart-1** [comment]
OW 可以删除 issue。但没必要， lock 了。
