### ISSUE TITLE
自动检查更新失败是为什么

### ISSUE THREAD

**Issue by Ka5en** [AmiyaBot/Amiya-Bot#104]
抱歉，纯萌新。很多东西不知道

![6)T0YW 2}{S 6QNY(H`UK7X](https://user-images.githubusercontent.com/106939528/172996010-30a3b35b-b408-4adb-b786-9cc5587de680.png)

**Comment by vivien8261** [comment]
不再提供更新检查服务了

**Comment by HYY1116** [comment]
> 不再提供更新检查服务了

原来的更新检查服务是怎么工作的，因为我一直没升级BOT，今天重启BOT的时候好像因为升级原因丢失了所有干员名之类的，所以想看看能不能自己搭一个本地的服务

**Comment by Initial-heart-1** [comment]
> > 不再提供更新检查服务了
> 
> 原来的更新检查服务是怎么工作的，因为我一直没升级BOT，今天重启BOT的时候好像因为升级原因丢失了所有干员名之类的，所以想看看能不能自己搭一个本地的服务

查阅源码。
