### ISSUE TITLE
“通过代码部署”中的资源挂了

### ISSUE THREAD

**Issue by LeafLight** [AmiyaBot/Amiya-Bot#116]
教程[”通过代码部署“](https://www.amiya.cn/docs/deployByCode.html#%E5%87%86%E5%A4%87%E5%A5%BD%E4%BD%A0%E7%9A%84-mirai-api-http)中[mirai-console-set-up](https://cos.amiyabot.com/tools/mirai-console-setup.zip)似乎挂了，手动配的话教程里的start.bat似乎是必要步骤。烦请大佬补上。

**Comment by vivien8261** [comment]
什么意思，教程明示是需要使用start.bat启动的

**Comment by vivien8261** [comment]
哦，setup包的cos关闭了，现在下载不了

**Comment by LeafLight** [comment]
> 哦，setup包的cos关闭了，现在下载不了

那么请问何时可以下载呢？

**Comment by vivien8261** [comment]
> > 哦，setup包的cos关闭了，现在下载不了
> 
> 那么请问何时可以下载呢？

https://pan.baidu.com/s/1vjORyF2WO1c0kF32EfdScA?pwd=8261

**Comment by LeafLight** [comment]
> > > 哦，setup包的cos关闭了，现在下载不了
> > 
> > 
> > 那么请问何时可以下载呢？
> 
> https://pan.baidu.com/s/1vjORyF2WO1c0kF32EfdScA?pwd=8261

十分感谢！
