### ISSUE TITLE
我想问一下，v5版本算是停止维护了吗？

### ISSUE THREAD

**Issue by hsyhhssyy** [AmiyaBot/Amiya-Bot#122]
我自己用v5版本的bot，修改了里面一堆bug，还添加了一大堆功能比如从wiki获取图片，自动更新gamedata等等，但是我看你们似乎是迁移到v6那边去了？那我是应该也尝试迁移到v6吗？还是说你们v5这个版本还会维护或者增加功能？那我可以顺势把我的一些改动提交过来。

**Comment by Initial-heart-1** [comment]
您好，感谢您选择 Amiya-Bot！
首先，您希望为 Amiya-Bot 作出自己的贡献，我们始终乐于看到这样的事情发生，并欢迎您随时提交 Pull Request！
但敬请知悉：

- v5 现仍是 Amiya-Bot 的“生产版本”。
- 我们没有计划继续对 v5 进行维护，包括安全和兼容性方面。
- v6 相较于 v5，架构有极大改变，在 v6 版本，我们对 core 部分进行了整体重构，对于 v5 存在的问题进行了很多改进。
- v6 相较于 v5，仍不够完善，尽管我个人推荐您选择 v6，但对于大规模的生产环境，这也许不是很明智的。但若是个人的用途，您尽可大胆尝试。
- 若您希望将您在 v5 上的开发进度迁移至 v6，可能需要您重新阅读 AmiyaBot 的开发文档。您可以 [在这里](https://www.amiyabot.com/develop/basic/) 找到相关内容。
- 若您希望将您在 v6 版本下的功能发布供全体用户选用，我们正筹划建立插件商店，敬请关注我们的最新消息。您可以加入我们的 [官方 QQ 频道](https://qun.qq.com/qqweb/qunpro/share?_wv=3&_wwv=128&appChannel=share&inviteCode=1W4sJux&appChannel=share&businessType=9&from=181074&biz=ka&shareSource=5) 以获得关于插件商店的最新动态。

最后，再次感谢您选择 Amiya-Bot，我们期待您的贡献！

**Comment by hsyhhssyy** [comment]
谢谢您的回复，不过QQ频道目前是内测，我还进不去.....
希望到时候更新插件功能的时候，您能在github上发一份guid

**Comment by Initial-heart-1** [comment]
> 谢谢您的回复，不过QQ频道目前是内测，我还进不去..... 希望到时候更新插件功能的时候，您能在github上发一份guid

guid 是什么？
另，记得通过上面的链接应该是可以直接加入内测的......

**Comment by Initial-heart-1** [comment]
您好！敬请注意：现在 V6 已经作为 AmiyaBot 的正式版发布！欢迎使用！

**Comment by hsyhhssyy** [comment]
好的，谢谢您的提醒，我现在逐步把我bot的代码迁移到v6
