### ISSUE TITLE
建议为console添加一个状态检查接口

### ISSUE THREAD

**Issue by Initial-heart-1** [AmiyaBot/Amiya-Bot#125]
通过该接口可检查 Amiya-Bot 是否运行。这对于云端的状态监测十分重要。
只需要一个 20x 状态码，这十分简单

**Comment by Initial-heart-1** [comment]
@vivien8261

**Comment by vivien8261** [comment]
一般来说……接口请求失败就相当于挂了

**Comment by Initial-heart-1** [comment]
直接请求会得到一个401状态码，upptime只认20x

**Comment by rhwong** [comment]
@Initial-heart-1  在uptime中创建监控项时，你可以自定义选择`有效状态码`，默认是200-299

**Comment by Initial-heart-1** [comment]
> @Initial-heart-1 在uptime中创建监控项时，你可以自定义选择`有效状态码`，默认是200-299

感谢，检查文档发现确有配置。
但请注意，**upptime** 不是 **uptime**，p 双写。

**Comment by Initial-heart-1** [comment]
![image](https://user-images.githubusercontent.com/63091661/199973078-099e5776-3e98-4eb1-a85a-af06d5faebb1.png)
事实上它的文档说只认 0x 而不是 xx。所以我怀疑你说的是否是一个东西。
