### ISSUE TITLE
希望可以提供标准onebot对接方式

### ISSUE THREAD

**Issue by rhwong** [AmiyaBot/Amiya-Bot#127]
不太清楚[mirai-api-http](https://github.com/project-mirai/mirai-api-http)是否属于onebot协议，看起来不像
希望可以提供标准onebot对接方式，这样可选择的登录端会更多，能够更好的和其他bot兼容
（刚把mirai换掉又要拾起来我直接痛苦面具了呜呜）

**Comment by Initial-heart-1** [comment]
您好，已提供 gocq 接入。您可以自行改动以连接至所有执行 OneBot v11 标准的适配器。另外，如果您改动，欢迎您提交 Pull Request！我们随时欢迎您的贡献！
感谢您对 AmiyaBot 的关注和支持！

**Comment by Initial-heart-1** [comment]
您好，已提供 gocq 接入。您可以自行改动以连接至所有执行 OneBot v11 标准的适配器。另外，如果您改动，欢迎您提交 Pull Request！我们随时欢迎您的贡献！
感谢您对 AmiyaBot 的关注和支持！
