### ISSUE TITLE
插件商店是不是还没开放?

### ISSUE THREAD

**Issue by hsyhhssyy** [AmiyaBot/Amiya-Bot#130]
### 功能描述

我过往V5写的一些有趣的小功能和小游戏，比如每日抽助理啊，骰娘啥的都已经陆陆续续迁移到v6了，不过目前插件商店还没开对吧，我看云端控制台按钮没做事件响应，而且商店里似乎还没有v5的那些功能以外的新功能。
PS：QQ频道的链接我确实进不去，如下图所示：
![IMG_9297](https://user-images.githubusercontent.com/5977110/197078363-d8597d1a-8d94-4c36-9235-28081917c691.PNG)

此外，我以前对V5的内置功能有一些微调，比如查询干员的时候，我给改成默认展示精二立绘了，现在这个功能以插件的方式提供了，是不是这些修改就没法操作了？插件是不是有自动更新？我本地的代码修改会被覆盖。

### 优点

我就是问一个小问题，功能我其实都做好了。

**Comment by vivien8261** [comment]
更改插件ID可以避免识别为同一个插件，发布插件的话近期在商讨发布方式……如果你有好的建议可以加群635398639

**Comment by Initial-heart-1** [comment]
确实还没有。近期上线，届时通知。
