### ISSUE TITLE
为User类加入可自定义的meta

### ISSUE THREAD

**Issue by hsyhhssyy** [AmiyaBot/Amiya-Bot#132]
### 功能描述

我在做一个别的功能的时候，遇到了一个问题，我想存储一些user related data，我在v5版本的实现方式是直接修改database里的user对象，但是v6版本你们准备以插件的形式提供功能变更，这个方法就不能用了，我目前是在本地磁盘做了一份持久化（以应对插件沙箱化），但是我觉得这样不优雅也不便维护。

我觉得你们要么提供一个给plugin直接访问数据库存储的能力（不推荐，有危险）
要么得给user对象（以及group对象）加入meta字段，然后提供一个函数来提供插件间相互隔离的持久化数据访问能力。

因为如果插件做的很复杂，需要持久化是很正常的情形，而plugins目录会随着插件更新，不安全，其他目录又不能假定，塞到resource下面又不优雅（"../resources"真的很蠢）。

### 优点

如上所述（

### 实现

我v5版本的做法是给user加入meta字段，实际上是个json字符串，然后提供简易的key value查找功能
v6版本可以类似的方式，加入meta字段和辅助函数来读写，里面key拼接上插件id来隔离，偷懒一点的话，拼接的部分可以让插件作者自己做

**Comment by Initial-heart-1** [comment]
考虑的很周到。建议提交一个 PR，或者等。

**Comment by hsyhhssyy** [comment]
那我先把我当前的代码提交一个PR好了

**Comment by Initial-heart-1** [comment]
你应该在 PR 中提到本 issue，这样会在合并时自动关闭它。在它确实解决前不推荐直接关闭。
e.g.
> balabala... #132 balabala...
