### ISSUE TITLE
AttributeError: 'Message' object has no attribute 'bot' 

### ISSUE THREAD

**Issue by hsyhhssyy** [AmiyaBot/Amiya-Bot#133]
### 问题描述

在官方开发文档的这个页面里：
https://www.amiyabot.com/develop/basic/messageObject.html
提到Message对象有一个属性bot
但是去看core的代码
![image](https://user-images.githubusercontent.com/5977110/197213694-6cc6a6f1-d08a-445d-8906-48ccf1999b49.png)
Message其实已经没有bot这个属性了
应修改为Instance属性

此外我是在尝试给用户私发消息的时候发现的
https://www.amiyabot.com/develop/basic/activeMessage.html
这份文档里提到
![image](https://user-images.githubusercontent.com/5977110/197214632-6cd9648f-ba08-433a-8e44-77861bd52ba6.png)
实际上direct_src_guild_id参数代码里也没用上，建议文档里也删掉

### 复现

如上所示，是文档建议

### Amiya-Bot 版本

6.0.0

**Comment by Initial-heart-1** [comment]
感谢反馈，请注意这不应该作为一个 Bug 提交。您可以通过创建一个空白的 issue 而不是使用模板来提交对文档的建议。具体是否改动需要问 @vivien8261 ，但是因为前述理由，这个 issue 将被关闭。
