### ISSUE TITLE
启动amiya.py提示ModuleNotFoundError:Nomodulenamed'amiyabot.adapters.cqhttp'

### ISSUE THREAD

**Issue by Lee0528Hub** [AmiyaBot/Amiya-Bot#138]
python3 amiya.py提示ModuleNotFoundError:Nomodulenamed'amiyabot.adapters.cqhttp'

环境是Ubuntu20.04、Python3.8.10、最新版兔兔、代码部署。用6.0.0版本的兔兔没问题。新版本兼容go-cqhttp后就一直没启动成功过。
![20221026](https://user-images.githubusercontent.com/110772808/198071797-2977c47d-9e24-43a4-ab47-a1e783412642.png)

**Comment by vivien8261** [comment]
pip install --upgrade amiyabot

**Comment by Lee0528Hub** [comment]
> 
已解决！
