### ISSUE TITLE
能否支持Windows server2012

### ISSUE THREAD

**Issue by LumiDust** [AmiyaBot/Amiya-Bot#149]
### 功能描述

想在服务器上运行，通过gocq的多连接功能，如：我现在连接nonebot2的ws与ff14的ws

### 优点

可以增加可拓展性与适配性

### 实现

我是无知小白只会提ls，磕头orz

**Comment by Initial-heart-1** [comment]
你好。
现在常见的 Windows Server 多为 2016 或 2019 甚至 2022。Windows Server 2012 实在是有些老，我们没有进行充分的验证明确 Amiya-Bot 可以在该环境下正常运行，但是同样的，我们也无法证明它无法正常运行，且，我们认为它应会正常工作。
由于这个需求较为罕见，可能需要您自行测试确认 Amiya-Bot 无法在该环境正常运行并提供详细信息。考虑到您的隐私，如果您不想公开发布这些信息，可以发送电子邮件至 support@amiya.cn。邮件中需包含指向该 issue 的链接。
您会有 3d 的回复时间，若过期仍未得到有效恢复，该 issue 会被关闭。

**Comment by LumiDust** [comment]
![_QXNWGMF(K _V57B{)XONJF](https://user-images.githubusercontent.com/116658416/200109405-f52214d7-f6bb-4cb6-88ad-5dd4da8cb290.png)
![image](https://user-images.githubusercontent.com/116658416/200109434-4bfd1dad-6c69-4c9a-b6e1-18202cc64d21.png)
在运行这个exe文件后会报错闪退

**Comment by Initial-heart-1** [comment]
报错提示您网络不佳。尝试连接代理重试。




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年11月5日(星期六) 下午3:47
To: ***@***.***&gt;; 
Cc: "Initial ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [AmiyaBot/Amiya-Bot] 能否支持Windows server2012 (Issue #149)





 

 
 在运行这个exe文件后会报错闪退

**Comment by LumiDust** [comment]
![image](https://user-images.githubusercontent.com/116658416/200210048-d2580a06-6671-428b-880a-478e51cd05c9.png)
你好，不好意思现在才回复，这是开了代理后的情况，已经测试过能够访问到github和谷歌

**Comment by Initial-heart-1** [comment]
确定您的 Git 正确配置后重试。

**Comment by Initial-heart-1** [comment]
如未解决请 Reopen 这个 issue。
