### ISSUE TITLE
[求助]“兔兔互动”插件：签到响应时间

### ISSUE THREAD

**Issue by ZhaoZuohong** [AmiyaBot/Amiya-Bot#153]
简述：“兔兔签到”与“兔兔查看我的信息”响应慢（~50s）

VPS 配置：单核 1G 内存
ping 延迟平均 155ms
数据库为默认的 SQLite

观察到以下现象：
- 使用“兔兔互动”插件时，“兔兔”命令的响应时间 <2s
- 使用“兔兔查看敌人扎罗”，响应时间 <3s
- 使用“兔兔签到”命令，响应时间 约为 50s
- “兔兔签到”命令响应前，未发现内存、CPU 与 Disk I/O 的使用率有明显上升

请问签到的响应时间是正常现象吗？有缩短的办法吗？应该从哪些方面进行排查呢？

**Comment by vivien8261** [comment]
请提高你的服务器配置

**Comment by Initial-heart-1** [comment]
推荐的服务器配置（以腾讯云为基准）：2H4G 及以上，带宽用户少时不低于 5Mbps，多时建议选用轻量应用服务器否则服务器费用可能过于高昂。

**Comment by ZhaoZuohong** [comment]
感谢推荐，我现在改用了双核 4G 内存的服务器，签到可以在 3 秒左右完成了。

**Comment by Initial-heart-1** [comment]
> 感谢推荐，我现在改用了双核 4G 内存的服务器，签到可以在 3 秒左右完成了。

考虑你反馈的时间，主要原因可能是内存不足。请知悉 AmiyaBot 被设计为大量使用 Chromium 来渲染页面以降低开发难度并使 UI 更美观。评估认为这需要至少 2G 的空闲内存才能确保正常工作。推荐你使用 go-cqhttp 以避免内存不足引发 OOM。
