### ISSUE TITLE
掉落数据：OF-F4 理智错误

### ISSUE THREAD

**Issue by ZhaoZuohong** [AmiyaBot/Amiya-Bot#154]
### 问题描述

明日方舟材料物品查询插件，对于轻锰矿的数据处理有误，OF-F4 关卡的理智消耗为 18，机器人提供的数据为 -1

### 复现

安装明日方舟材料物品查询插件，查询轻锰矿

### Amiya-Bot 版本

`bd50e97ae32b12dfbabac08977f2716fdfdcb7e6`

### 其他插件版本

明日方舟材料物品查询 1.1

### 日志

```text
无
```

### 补充信息

无

**Comment by vivien8261** [comment]
这部分是企鹅物流的数据，仅供参考。

**Comment by ZhaoZuohong** [comment]
企鹅物流网页的数据是正确的

**Comment by vivien8261** [comment]
OF-F4 在游戏数据里理智消耗就是 -1，不要去想YJ是怎么改为 18 的

![image](https://user-images.githubusercontent.com/34387011/200717194-c3bc38bf-4040-48c7-b511-f95a524dd163.png)

**Comment by Initial-heart-1** [comment]
或可提供一新的提交系统，类似于企鹅物流。不过真有这个必要？
