### ISSUE TITLE
干员专精材料：图片不完整

### ISSUE THREAD

**Issue by ZhaoZuohong** [AmiyaBot/Amiya-Bot#155]
### 问题描述

![-8fe81dba239b8f2](https://user-images.githubusercontent.com/34163622/200708869-5968dc4f-582b-4d4c-9148-46d0d94129f3.png)

### 复现

![Screenshot_20221109-084617-312](https://user-images.githubusercontent.com/34163622/200708622-fbd0de2c-51ad-4f29-bffb-14a211e2288d.png)

### Amiya-Bot 版本

`bd50e97ae32b12dfbabac08977f2716fdfdcb7e6`

### 其他插件版本

明日方舟干员资料 1.8

### 补充信息

多试几次后能够发出完整图片

**Comment by vivien8261** [comment]
请提高你的服务器配置。或使用启动参数延长渲染时间。

```bash
python amiya.py --browser-render-time 1000
```

**Comment by ZhaoZuohong** [comment]
加了启动参数后没有问题了，非常感谢！

**Comment by Initial-heart-1** [comment]
是时候在手册里加上一句了：遇到渲染问题时，请在**你使用的设备**上尝试重现，而不是在**生产环境的服务器**上！
