### ISSUE TITLE
适应手机的图片比例与尺寸

### ISSUE THREAD

**Issue by ZhaoZuohong** [AmiyaBot/Amiya-Bot#157]
### 功能描述

生成适合手机查看的图片（宽度更小），增大图片尺寸（使字体更清晰）

### 优点

在手机上有更佳的阅读体验

### 实现

如果图片以浏览器截图的方式生成，可以在调用 playwright 时指定设备或页面的缩放和尺寸：

<https://playwright.dev/python/docs/api/class-browser#browser-new-page>

- `viewport` 可以修改分辨率
- `device_scale_factor` 可以修改缩放

例如 iPhone 的分辨率为 390x844，缩放为 3

这样得到的图片更清晰，放大后字不会模糊，而且图片体积不会很大。

**Comment by vivien8261** [comment]
不同的分辨率意味着需要不同的 `设计图`，尚未有任何小组成员能够大量修改现有的设计。如你有余力，可以自行修改。

分辨率修改可以参考启动参数：https://www.amiyabot.com/develop/advanced/startupParameter.html
