### ISSUE TITLE
一个关于实例IP变化导致的bug

### ISSUE THREAD

**Issue by hsyhhssyy** [AmiyaBot/Amiya-Bot#161]
### 问题描述

我不确定bug在哪儿，在深入检查代码之前，先报到这里。
具体经过是，我的服务器在重启之后，mcl docker的ip发生了变化，导致原来的mcl无法连接。

1、我点击实例的编辑，修改ip以后，他不会自动刷新连接，必须要我做点什么
2、我点击关闭再点击打开来让他重连。
然后他就会不停的报错：
![image](https://user-images.githubusercontent.com/5977110/203163729-ca3a8de8-d167-4eee-adf9-382e5b344f9a.png)

但是，此时bot的功能是正常的。

这个错误会持续报告数十分钟，我怀疑会一直报告下去。
后面我重启了bot，就不再出错了。

### 复现

如上

### Amiya-Bot 版本

6.0.0

**Comment by Initial-heart-1** [comment]
如果可能，下次请将 issue 写的更明白些。
一开始我的简单看了一下，得到的信息是您实例 IP 变动，无法按原配置连接到实例，故准备关闭 issue。
仔细查看后，发现您似乎在说因为 **在未断开连接时直接修改了实例的网际协议地址导致在重启 AmiyaBot 前无法正常连接到实例**。
下次或许可以略去 **为什么我这么做**，除非确实需要它才能准确说明。
另外，这个 issue 或许应该在 core 仓库提出。
@vivien8261 或许应该转移 issue。

**Comment by hsyhhssyy** [comment]
> 如果可能，下次请将 issue 写的更明白些。 一开始我的简单看了一下，得到的信息是您实例 IP 变动，无法按原配置连接到实例，故准备关闭 issue。 仔细查看后，发现您似乎在说因为 **在未断开连接时直接修改了实例的网际协议地址导致在重启 AmiyaBot 前无法正常连接到实例**。 下次或许可以略去 **为什么我这么做**，除非确实需要它才能准确说明。 另外，这个 issue 或许应该在 core 仓库提出。 @vivien8261 或许应该转移 issue。

其实你理解的还不对，我之所以说这么多就是因为我很难准确描述这个错误。
我的错误其实是 **bot重启后，已无法连接某个实例，此时修改该实例的配置，会导致意外的持续报错，但是功能正常**

**Comment by vivien8261** [comment]
这个问题应该是可以复现的，根源代码应该是在 V6-dev 分支下 core/server/bot.py 第 80 行和第 103 行。由于 console 服务在修改配置时启动了新的实例却没有关闭同 appid 的另一个实例导致。

**Comment by vivien8261** [comment]
已确定原因是 core 内的一个 bug 导致。[已修复](https://github.com/AmiyaBot/Amiya-Bot-core/commit/95a39f1d93f708712fb9d17dfe784d74521e3e3d)

**Comment by Initial-heart-1** [comment]
> > 如果可能，下次请将 issue 写的更明白些。 一开始我的简单看了一下，得到的信息是您实例 IP 变动，无法按原配置连接到实例，故准备关闭 issue。 仔细查看后，发现您似乎在说因为 **在未断开连接时直接修改了实例的网际协议地址导致在重启 AmiyaBot 前无法正常连接到实例**。 下次或许可以略去 **为什么我这么做**，除非确实需要它才能准确说明。 另外，这个 issue 或许应该在 core 仓库提出。 @vivien8261 或许应该转移 issue。
> 
> 其实你理解的还不对，我之所以说这么多就是因为我很难准确描述这个错误。 我的错误其实是 **bot重启后，已无法连接某个实例，此时修改该实例的配置，会导致意外的持续报错，但是功能正常**

现在你不是成功的准确描述了故障么？真诚的推荐您不要急着发 issue，或许可以让它变得更易读后再发出来（

**Comment by hsyhhssyy** [comment]
> 

其实这里还是有歧义的，应该改为bot启动时，如果不能连接某个实例，此时修改该实例的配置，会导致持续报错。
但是我觉得，前因后果都描述清楚，有助于定位错误的原因。
目前这个错误比较简单，但是对于比较复杂的错误，可能会出现需要复现场景，或者从操作流程上找原因的情况。
我之所以能总结出这个问题，是因为我对代码有个大概的了解，如果对代码不甚了解，可能不一定能总结出问题，并且意识到原因。

比如，这里我的描述中，我还隐含提到了一个事情，就是修改配置的时候，我没有观察到实例的启动。我是通过关闭再打开，尝试触发启动。
我现在仍然不知道，修改实例配置并保存后，是否会触发一个实例重启。

**Comment by Initial-heart-1** [comment]
> > 
> 
> 其实这里还是有歧义的，应该改为bot启动时，如果不能连接某个实例，此时修改该实例的配置，会导致持续报错。 但是我觉得，前因后果都描述清楚，有助于定位错误的原因。 目前这个错误比较简单，但是对于比较复杂的错误，可能会出现需要复现场景，或者从操作流程上找原因的情况。 我之所以能总结出这个问题，是因为我对代码有个大概的了解，如果对代码不甚了解，可能不一定能总结出问题，并且意识到原因。
> 
> 比如，这里我的描述中，我还隐含提到了一个事情，就是修改配置的时候，我没有观察到实例的启动。我是通过关闭再打开，尝试触发启动。 我现在仍然不知道，修改实例配置并保存后，是否会触发一个实例重启。

我个人认为，如果可能，给予尽可能简明的、易读的信息比详细的信息更为重要。需要的更为详细的信息可以通过询问得到，而简明易读的信息则能帮助开发者最快的了解问题可能出在哪里，以及是否有价值。

**Comment by Initial-heart-1** [comment]
只要不答非所问，进一步的询问是完全可以接受的，也是必要且几乎一定会发生的。故可能不需要在打开 issue 时提供极为详细的信息，这往往并不会给排障带来帮助。
