### ISSUE TITLE
兔兔互动插件报错

### ISSUE THREAD

**Issue by SunshineboyZj** [AmiyaBot/Amiya-Bot#182]
### 问题描述

兔兔互动插件出现报错，暂时未发现影响哪些功能。可以问下这是什么原因呀

### 复现

安装兔兔互动插件，隔几分钟就蹦出来一大段这样的报错

### Amiya-Bot 版本

v6.0.14-master

### 其他插件版本

安装了以下插件，均为最新版（截止至2.27 18:37）
[1]明日方舟敌方单位查询
[2]明日方舟模拟抽卡
[3]理智恢复提醒
[4]明日方舟合成玉计算
[5]明日方舟材料物品查询
[6]明日方舟干员资料
[7]明日方舟公招查询
[8]明日方舟关卡查询
[9]兔兔猜干员
[10]大帝的CYPHER挑战
[11]词语替换
[12]自定义回复
[13]每日新闻
[14]网易云点歌
[15]pixiv搜图
[16]抽卡记录查询
[17]熵的剧情查询插件
[18]兔兔互动

### 补充信息

![IMG_20230227_183336](https://user-images.githubusercontent.com/81549837/221541682-c9c33b1b-0cda-414a-a2c6-6d7152e82e52.jpg)

**Comment by SunshineboyZj** [comment]
有时候会出现，出现挺玄学的

我得了一种看到报错就要死的病（doge

**Comment by SunshineboyZj** [comment]
很频繁，隔一段时间就出现这些报错

**Comment by vivien8261** [comment]
GO-CQ事件的问题，不影响使用，后续计划修复
