### ISSUE TITLE
语音文件下载失败

### ISSUE THREAD

**Issue by SunshineboyZj** [AmiyaBot/Amiya-Bot#183]
### 问题描述

语音文件下载失败，在兔兔猜干员、查干员语音情况下出现

### 复现

1.兔兔猜干员-高级
2.兔兔查看XX中文/日文语音1

### Amiya-Bot 版本

v6.0.14-master

### 日志

```text
无相关日志
```

### 补充信息

![-fd7b3887a374c52](https://user-images.githubusercontent.com/81549837/221542756-820be5fc-0472-4e65-87fc-045770578474.png)
![Screenshot_20230227_171814](https://user-images.githubusercontent.com/81549837/221542952-0c896082-a7cb-4beb-bf0b-0f76bb2d05e9.jpg)
![Screenshot_20230227_171819](https://user-images.githubusercontent.com/81549837/221542972-127627be-7a59-41ee-9dfd-1e9c10356a13.jpg)

**Comment by vivien8261** [comment]
已修复，请更新主分支代码
