### ISSUE TITLE
AmiyaBot Console的跨域问题

### ISSUE THREAD

**Issue by DoyoDia** [AmiyaBot/Amiya-Bot#209]
### 问题描述

使用AmiyaBot Console配置服务地址时提示"ERR_NETWORK接口请求失败"然而直接访问请求的连接是有返回的。浏览器控制台报错：xhr.js:220  Mixed Content: The page at 'https://console.amiyabot.com/#/plugin' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://100.84.213.38:8088/bot/link'. This request has been blocked; the content must be served over HTTPS.

![Z4HEFQ{KA`5`$USTN`19XBB](https://user-images.githubusercontent.com/79502694/236656576-c6bb080a-3c39-4992-9949-90f74bb34225.png)

### 复现

1.使用wireguard等vpn服务连接内网
2.在AmiyaBot Console使用http的内网地址访问
3.等待提示ERR_NETWORK接口请求失败

### Amiya-Bot 版本

v6.2.3-fix-master

### 补充信息

edge可以在设置-网站权限-不安全的内容 将AmiyaBot Console加入允许列表

**Comment by Initial-heart-1** [comment]
无效 issue，对问题理解不对。
您使用了 HTTPS 的 Console，不允许降级访问。

**Comment by DoyoDia** [comment]
用http://console.amiyabot.com/ 确实就没这问题了（）

**Comment by Initial-heart-1** [comment]
请不要更新这个 issue 的状态，它应该以 not planned 被关闭

**Comment by Initial-heart-1** [comment]
在FAQ里有对你的问题进行了描述：
![image](https://user-images.githubusercontent.com/63091661/236657673-d0581c55-93fc-45e4-bbed-f45fcdd8997e.png)
da
当然，不推荐这么做，推荐的做法是使用反向代理升级连接，FAQ将尽快修订。

**Comment by Initial-heart-1** [comment]
下次在打开 issue 时请先深思熟虑，确保你已检查文档。特别是，作为 Bug 提交时 issue 将具有较高优先级，这时被关闭说实在有些尴尬

**Comment by DoyoDia** [comment]
十分抱歉
感觉或许在文档链接控制台的那一步的最下面，加一个连接到[FAQ关于连接控制台](https://www.amiyabot.com/guide/deploy/faq/commonProblem.html#%E6%97%A0%E6%B3%95%E8%BF%9B%E5%85%A5%E6%8E%A7%E5%88%B6%E5%8F%B0)的超链接会更方便一点。

**Comment by Initial-heart-1** [comment]
不现实。为每一个可能出现问题的地方添加一个FAQ的超链接，工作量太大且不好维护。
事实上，我们在频道中对提问前的检查列了清单，可以避免出现这些问题。
