### ISSUE TITLE
请问，能否使用red部署QQ群机器人？如果不能，请问作者是否有计划添加使用red部署QQ机器人的方法？

### ISSUE THREAD

**Issue by LiuHsouno** [AmiyaBot/Amiya-Bot#263]
### 建议

如题

**Comment by Initial-heart-1** [comment]
用户您好，amiyabot 现已支持接入按 `OneBot 11/12` 标准进行交互的项目。详情请见：https://www.amiyabot.com/develop/adapters/onebot11.html
https://www.amiyabot.com/develop/adapters/onebot12.html

**Comment by Initial-heart-1** [comment]
由于众所周知的原因以及 red 本身并没有什么东西，目前不考虑特别为 red 添加适配，但是应当不影响基本的使用，且可以通过外部处理完全转换到ob11/12，详见标准文档。

**Comment by vivien8261** [comment]
你应该是指对接 [Chronocat](https://github.com/chrononeko)，但是 Chronocat 本身并不完善且已经处于停止维护边缘状态，所以暂时不考虑了。
[增加 Chronocat 适配器](https://github.com/AmiyaBot/Amiya-Bot-core/issues/70)

**Comment by Initial-heart-1** [comment]
@vivien8261 不一定是 Chronocat，但 Red 首先东西很少，然后跟 ob11/12 记得是有交集的，也就是说可以直接当做 ob 去连，只是不会完全按照预期工作。这个问题（Chronocat 适配）记得之前办公室有说过的。
