### ISSUE TITLE
部署相关的的提议

### ISSUE THREAD

**Issue by 99Mr-Z** [AmiyaBot/Amiya-Bot#270]
### 建议

能否提供一个较为完善的docker部署方式吗？
           通过docker部署可能更为简单些易用些，目前想用来作为主域名的一个主域名的访问交互页面，并没有计划添加到其他聊天服务上作为机器人使用，若条件允许可以再允许调用一些常见的国内大模型进行chatgpt式的访问交互，提供更通用的使用方式，（主要现在大模型使用成本还是挺低的）

**Comment by Initial-heart-1** [comment]
用户您好，感谢您选择 Amiya-Bot！
对于您的议题，现向您答复如下：
- 关于 docker 部署
我们曾讨论过该问题，目前得出的结论是应当不必要一定支持 docker 部署。
除非您有充足的理由说明 “**为什么 Amiya-Bot 需要 docker？**”，否则我们目前将不考虑添加 docker 部署方式。
尽管如此，**您仍可以在 docker 容器内运行 Amiya-Bot**，只不过部署过程是手动的。
当然，如果您乐意，我们非常欢迎您向我们提交 Pull request 以实现 docker 部署，**只要它能够通过我们的 Review**。

- 关于大模型
请注意，**AmiyaBot 项目组在目前没有任何从框架层面支持大模型接入的计划，且并不欢迎关于大模型的贡献。**
尽管我们不推荐，但是您仍可以在 Amiya-Bot 插件市场中找到其他开发者上传的相应插件以用于接入大模型，或是自行编写插件，详见我们的 [插件开发文档](https://www.amiyabot.com/develop/plugin/)。
特别的，我们必须提示您，在 Amiya-Bot 支持的大多适配器中，引入大模型是**极其严重的违规行为**，甚至在某些情形下**可能涉及违法**，敬请留意。

最后，再次感谢您选择 Amiya-Bot，（如果您希望如此）我们期待并欢迎您的贡献！

**Comment by Initial-heart-1** [comment]
议题已答复且认定 won‘t fix，我将先行关闭此议题。
如果您有任何需要，请重新打开它，并附上补充说明。谢谢。

**Comment by 99Mr-Z** [comment]
> 用户您好，感谢您选择 Amiya-Bot！ 对于您的议题，现向您答复如下：
> 
> * 关于 docker 部署
>   我们曾讨论过该问题，目前得出的结论是应当不必要一定支持 docker 部署。
>   除非您有充足的理由说明 “**为什么 Amiya-Bot 需要 docker？**”，否则我们目前将不考虑添加 docker 部署方式。
>   尽管如此，**您仍可以在 docker 容器内运行 Amiya-Bot**，只不过部署过程是手动的。
>   当然，如果您乐意，我们非常欢迎您向我们提交 Pull request 以实现 docker 部署，**只要它能够通过我们的 Review**。
> * 关于大模型
>   请注意，**AmiyaBot 项目组在目前没有任何从框架层面支持大模型接入的计划，且并不欢迎关于大模型的贡献。**
>   尽管我们不推荐，但是您仍可以在 Amiya-Bot 插件市场中找到其他开发者上传的相应插件以用于接入大模型，或是自行编写插件，详见我们的 [插件开发文档](https://www.amiyabot.com/develop/plugin/)。
>   特别的，我们必须提示您，在 Amiya-Bot 支持的大多适配器中，引入大模型是**极其严重的违规行为**，甚至在某些情形下**可能涉及违法**，敬请留意。
> 
> 最后，再次感谢您选择 Amiya-Bot，（如果您希望如此）我们期待并欢迎您的贡献！

感谢回复，希望使用docker部署只是因为更简单些吧，通常对于一些环境依赖性更低，使更多的家用nas也能自行布置使用，不必纠结于所使用的linux发行版是否支持当前版本的amiya bot的部署。
若并不希望增添docker的部署也是合情合理的，在此仍然感谢各位开发者的贡献，开发出更多易用的项目分享使用，谢谢

**Comment by Initial-heart-1** [comment]
准确来说，是因为并没有必要。
因为 amiyabot 与 Amiya-Bot（前者也被我们称作 core）实际上本身就具备一定的跨平台能力，因为它们使用 Python 编写。
在未经官方测试的发行版系统上运行上述服务通常是完全可以做到的，只需要确保我们的上游依赖在目标环境没有任何问题，常见的设备和发行版系统均满足该条件。甚至，曾有用户回报其成功在 Android（ARM 设备） 上运行 Amiya-Bot 及配套适配器。
请您理解，作为一个小型开源项目，我们不太可能有足够的能力对广泛的发行版进行测试，并不太可能为这些版本提供细致的技术支持。

现在，对于 Amiya-Bot，官方支持的操作系统如下：
- Windows 10、Windows Subsystem for Linux (WSL) 或 Windows Server 2012 及以上系统
- MacOS 11 (Big Sur) 及以上系统
- Linux 系统官方支持 Debian 11、Ubuntu 18.04 以及 Ubuntu 20.04

在支持列表外的系统并不意味着无法运行，只是我们可能不会对其编写相应的文档，并且如果在信息不足或出现特定于平台的问题时可能不会响应这些支持请求。
并且，我已向您说明，您可以手动操作 docker 容器进行部署，这与一般的 docker 部署并无任何不同，除去部署操作由人工完成。
有关于部署 Amiya-Bot 的更多信息，敬请查阅我们的 [部署文档](https://www.amiyabot.com/guide/deploy/getStarted.html)。
