### ISSUE TITLE
【注意】发现可疑的issue记录 请勿点击其内的链接

### ISSUE THREAD

**Issue by Initial-heart-1** [AmiyaBot/Amiya-Bot#286]
### 内容

issues #285
> _We have detected a security vulnerability in your repository..._

这个 issue 是个恶意诈骗并且已经被 github ban 了
其中的一个网址，请勿点击，以防出现问题。
此 issue 仅用于记录和触发 Email 通知。

**Comment by vivien8261** [comment]
啊？
