### ISSUE TITLE
部署出错

### ISSUE THREAD

**Issue by KokuraSona** [AmiyaBot/Amiya-Bot#299]
### 问题描述

在Windows Server 2012/Windows 10上均遇到完全一致的错误
已确认Git安装和网络通畅
<img width="824" alt="スクリーンショット 2024-12-15 16 48 10" src="https://github.com/user-attachments/assets/de4a96a5-6784-4093-830e-4672dca790cd" />

### 复现

部署时触发

### Amiya-Bot 版本

AmiyaBot-v6.5.6-win32

**Comment by vivien8261** [comment]
感谢指出！已在新版本修复这个问题，下载6.5.7即可 #300
