### ISSUE TITLE
亿些功能建议和小问题

### ISSUE THREAD

**Issue by Initial-heart-1** [AmiyaBot/Amiya-Bot#31]
**由于本人措辞有问题，太皮了，导致一些误会，我的问题，我认，不会再做这样的事，谁都让他自己写格式去**

以下是部署项目近三个月以来收集的一些经用户反馈与我筛选认为需要优化的问题。

#### 1.1 优化干员档案查询

现在，想要查询一个干员的档案需要的操作比较复杂，如果想要查询一个干员的所有档案资料是非常繁琐的，但单独查询大多数时候并没有意义。
建议由需要一项项查询档案改为一次性呼出。
从用户角度看，应该是这样：
阿米娅查看（干员名称）（档案标题）x N → 阿米娅查看（干员名称）的档案资料（**此处合并前 x N 次指令的输出结果**）

#### 1.2 优化干员立绘（皮肤）查询

如果想查询某干员的精一或精二立绘，可以直接使用“精一/精二”作为关键词而非现在的“精英一/精英二”，查询皮肤可直接使用皮肤名称检索而非先呼出阿米娅，查找皮肤列表后使用“阿米娅查看（干员名）第 N 个立绘”来检索。

#### 1.3 优化干员语音查询

如果想查询某干员的语音，在未检索到语音标题时返回语音列表以供检索。

#### 1.4 优化干员晋级材料查询

如果想查询某干员的晋级材料，提供一个指令查询将该干员升级至满配需要多少材料。

例如指令为：阿米娅查询银灰满配材料
返回：
全技能专三总共需要的材料
一技能专三总共需要的材料
二技能专三总共需要的材料
三技能专三总共需要的材料

#### ~~（这是一个新功能）1.5  干员生日查询、订阅~~
详见 #40 

#### 2.1 优化模拟抽卡卡池列表

很多时候，用户不会去刻意记忆某卡池的名称（我相信你也不会）
所以，建议在卡池列表的返回数据中添加当期 up 的干员名称，以便检索。

####  2.2（请注意，这是一个新功能建议）添加模拟抽卡抽卡记录

顾名思义，加个干员盒子，记录用户抽取到的干员及潜能数，供用户查询。
我的实现思路：
大家都知道，每一个干员都有一个唯一的数字 id，那么，在数据库用户表中添加一个字段，记录每个用户抽取到的干员 id，潜能可以另开亿个字段记下来。
那么可以在用户抽卡时对抽卡结果进行处理（可能会导致结果返回延迟较高），或者采用延迟处理，先将用户的抽卡数据缓存，在闲时（每分钟消息量小于一个数值）时处理数据并操作数据库。
查询时，提出这个建议的人是这么设想的：
在返回开头列出现有的总干员数量，然后列出六星、五星、四星的数量
然后将所有干员的头像排好，获得了的点亮为彩色，没有获得的干员头像黑白
我个人再加一点：查询也需要消耗寻访凭证。不然服务器扛不住啊扛不住

###  3.（请注意，这个是我自己提的）别名识别添加审核可选择 Amiya 私聊~~与全局应用该别名~~。

理由是，console 对小屏设备太太太太不友好了......~~***（或许可以开坑移动适配？）***~~
然后就是，方便
还有就是，建议顺便加个寻访凭证奖励，鼓励用户~~当工具人~~添加别名
另外，在记录审核请求时，记得**全局查重**，以免一打开后台一半重复的

### ~~（请注意，此处大多为新功能）4.其他数值查询与计算~~
详见 #40

**Comment by 1072324725** [comment]
作者大大，为啥我这个兔子的签到不会刷新啊，第一天签到了，后面一直说已经签到了....

**Comment by Initial-heart-1** [comment]
> 作者大大，为啥我这个兔子的签到不会刷新啊，第一天签到了，后面一直说已经签到了....

你好，兔妈最近 007 ，我深感同情，这意味着原作者短时间内无法向你提供帮助，请加入 readme 下方的开发群，其他开发者也许可以帮助你，最后，提问务必附上日志！

**Comment by Initial-heart-1** [comment]
> 作者大大，为啥我这个兔子的签到不会刷新啊，第一天签到了，后面一直说已经签到了....

你好，兔妈最近 007 ，我深感同情，这意味着原作者短时间内无法向你提供帮助，请加入 readme 下方的开发群，其他开发者也许可以帮助你，最后，提问务必附上日志！

**Comment by Initial-heart-1** [comment]
以后这些问题请新开一个 issue 提问哦

**Comment by vivien8261** [comment]
已采纳部分建议建立 issue
