### ISSUE TITLE
无法下载干员语音

### ISSUE THREAD

**Issue by MistEO** [AmiyaBot/Amiya-Bot#38]
emmm不知道是不是我自己的问题。
这里的url，少了`http:`，导致后面语音下载失败。我试了下切到原版的上面也是同样的问题，手动加上`http:`之后就可以正常下载了

![image](https://user-images.githubusercontent.com/18511905/141691555-0d452326-55bc-4a59-b692-79b698d769c2.png)
![image](https://user-images.githubusercontent.com/18511905/141691664-f6d60d6b-a47c-4847-bf09-f8d7af6f2afb.png)

**Comment by MistEO** [comment]
我的修改请参考 https://github.com/InvoluteHell/Amiya-Bot/commit/c2f79f3295f07c0ceea5f7a32b4cd8629dc32cca

**Comment by fatinghenji** [comment]
同样存在语音加载问题，我以为是需要手动触发下载（

**Comment by MistEO** [comment]
> 同样存在语音加载问题，我以为是需要手动触发下载（

懂了，这就pr =。=
