### ISSUE TITLE
亿点点功能

### ISSUE THREAD

**Issue by Hindleia** [AmiyaBot/Amiya-Bot#40]
1免兔计算狗粮功能
1.1 计算干员升级所需的狗粮和龙门币数量
输入0~90级需要多少高级/中级/低级/基础作战记录(后期可以简化关键字呼叫)输出需要12004 (瞎编的数字)高级作战记录
1.2换算狗粮之间的数量
输入兔兔1高级等于多少中级/低级/基础
输出计算结果(狗粮数量和龙门币数量)
2查询干员专三到一级技能数值,希望实现-个查看 -一个技能全部数值而且是一个图浏览输入查看单个技能数值
例如:兔兔查看42三技能数值
输出结果
三技能一级数值贴图
三技能二级数值贴图
三技能三级数值贴图
以此类推到专三
全部合并成一-图查看
3查看半个月之内的方舟频道热门前十视频
输入前十热门明日方舟视频个人认为缩写前十视频的关键词就可以了
输出前十视频名单
格式:标题+bv号
top1视频格式
top2视频格式
top3视频格式
以此类推
4兔兔关于干员生日功能的部分
4.1是查看这个月/这天干员生日
输入兔免这个月有谁生日
输出，渲染- -张这个月的日历，上面标记干员生日具体日期
输入免兔今天有谁生日
输出，回复今天(写上今天日期, 1.22) 42生日,送上祝福台词
多个干员生日同一天情况, 安哲拉,空弦生日,祝福台词
4.2查看干员生日
输入兔兔42生日几号
输出42生日1.22
4.3订阅干员生日功能,订阅之后,到期时推送信息
输入兔兔订阅42生日(可以优化-下订阅台词)
输出,艾特订阅用户，提醒今天42生日

**Comment by Initial-heart-1** [comment]
注意格式，建议使用 Markdown 格式化
另外，注意 GFM 与标准 Markdown 的区别
如果你认可，也可以关闭这个 issues，由我整合进我的 issues 中
另外，我想这本身就可以直接在我的 issues 下回复，而不是新开一个 issues，这在一定程度上导致了资源浪费

**Comment by vivien8261** [comment]
已采纳部分建议建立 issue
