### ISSUE TITLE
关于别名识别在部分功能中影响正常使用的问题

### ISSUE THREAD

**Issue by nezumyao** [AmiyaBot/Amiya-Bot#52]
兔兔添加到了第42号卡池，由于42被替换为史尔特尔，导致“兔兔切换42号卡池”的命令无法被正确识别到。

![img](https://user-images.githubusercontent.com/29001811/149687103-8872312f-8655-4b17-9004-ee51f51fe254.png)

**Comment by vivien8261** [comment]
目前没有很好的方法可以解决此问题，“42”属于常用一般词汇，而且还是数字，极容易发生冲突。

**Comment by vivien8261** [comment]
目前没有很好的方法可以解决此问题，“42”属于常用一般词汇，而且还是数字，极容易发生冲突。

**Comment by Initial-heart-1** [comment]
> 目前没有很好的方法可以解决此问题，“42”属于常用一般词汇，而且还是数字，极容易发生冲突。

可以尝试引入中文数字解决
目前可以尝试直接输入卡池名称
@nezumyao

**Comment by vivien8261** [comment]
已在别名识别审核时拒绝纯数字别名
