### ISSUE TITLE
资源无法更新到最新

### ISSUE THREAD

**Issue by Rovniced** [AmiyaBot/Amiya-Bot#53]
私聊中输入 `强制更新` 后 依旧无法更新下载失败的资源文件
![QQ截图20220122001918](https://user-images.githubusercontent.com/52170460/150562817-f2dba8e0-e864-40bb-99b4-10e3e53ef2dd.png)

已有的资源文件似乎很旧
![2YUJ(A`~H V)I0$LR3~9GJ4](https://user-images.githubusercontent.com/52170460/150562881-aaf55a14-8051-4d5d-95d1-82466fd78575.png)

尝试手动从 https://github.com/yuanyan3060/Arknights-Bot-Resource 此处下载资源文件替换（似乎文件夹名字有点不一样，自己手动改了下），依旧不是最新版

找了半天 没找到其他资源的下载地址，请问如何手动使资源更新到最新？

**Comment by vivien8261** [comment]
因为更新服务器已经迁移到 cos，如果不是最近的版本，可能没办法更新到最新版。<br>
[最新版下载](https://cos.amiyabot.com/package/AmiyaBot-v4.1.4-fix-1.zip) <br>
最新版修改了数据的下载地址，可以尝试用这个。你直接下载 Arknights-Bot-Resource 仓库也是一样的。但是需要修改文件夹名

**Comment by Rovniced** [comment]
> 因为更新服务器已经迁移到 cos，如果不是最近的版本，可能没办法更新到最新版。 [最新版下载](https://cos.amiyabot.com/package/AmiyaBot-v4.1.4-fix-1.zip) 最新版修改了数据的下载地址，可以尝试用这个。你直接下载 Arknights-Bot-Resource 仓库也是一样的。但是需要修改文件夹名

用的是最新版 无法更新

**Comment by Initial-heart-1** [comment]
有部分资源是缺失的，不需要管，不影响使用哈（比如干员信物啥的）
另外，不知道从哪个版本开始，已经不会自动同步卡池了，需要你自己通过 console 手动添加

**Comment by asdqp233** [comment]
> 有部分资源是缺失的，不需要管，不影响使用哈（比如干员信物啥的） 另外，不知道从哪个版本开始，已经不会自动同步卡池了，需要你自己通过 console 手动添加


请问有添加方式的方法说明吗

**Comment by Rovniced** [comment]
> 有部分资源是缺失的，不需要管，不影响使用哈（比如干员信物啥的） 另外，不知道从哪个版本开始，已经不会自动同步卡池了，需要你自己通过 console 手动添加

好的 已经解决 谢谢
