### ISSUE TITLE
这个前端是拿什么框架开发的，挺清爽的

### ISSUE THREAD

**Issue by dongrixinyu** [AmiyaBot/Amiya-Bot#57]
这个前端是拿什么框架开发的，挺清爽的

**Comment by Initial-heart-1** [comment]
你好，console 吗？
全部由 @vivien8261 完成

**Comment by vivien8261** [comment]
console 使用 vue + elementUI 完成，可查看 [Amiya-Bot-console](https://github.com/AmiyaBot/Amiya-Bot-console)
