### ISSUE TITLE
建议优化操作逻辑

### ISSUE THREAD

**Issue by Initial-heart-1** [AmiyaBot/Amiya-Bot#76]
现在很多功能需要也只能“两步走”，也就是先唤出列表再回复序号
建议是可以选择直接带上序号来一次查询
比如我要查莫斯提马的某档案，我可以直接用
`阿米娅莫斯提马档案[列表中的序号]`
而不是
`阿米娅莫斯提马档案`
`[列表中的序号]`
在相对大量的数据查询时，这会更加方便，也更节省资源

**Comment by FogFoge** [comment]
整的我想写了



在 2022-04-17 17:35:02，"Initial-heart" ***@***.***> 写道：

现在很多功能需要也只能“两步走”，也就是先唤出列表再回复序号
建议是可以选择直接带上序号来一次查询
比如我要查莫斯提马的某档案，我可以直接用
阿米娅莫斯提马档案[列表中的序号]
而不是
阿米娅莫斯提马档案
[列表中的序号]
在相对大量的数据查询时，这会更加方便，也更节省资源

**Comment by FogFoge** [comment]
整得我想写了

**Comment by Initial-heart-1** [comment]
> 整得我想写了

又没 Assignees，你写呗
冲着你这句话兔妈得给你上 Assignees
