### ISSUE TITLE
Bug：在运行amiya的时候出现Runtime Error

### ISSUE THREAD

**Issue by FogFoge** [AmiyaBot/Amiya-Bot#91]
![image](https://user-images.githubusercontent.com/62325603/166670348-68da0997-948c-46be-a97d-916bed57ce1b.png)

如图，Amiya-Bot-dev目录是从主仓库V5-master分支clone下来的，chromium已安装，版本信息如图，依赖已安装。

很离谱，今天上午在写新功能的时候一点事没有，然后等我尝试新建一个dev的git分支后，运行就出现了这个问题。然后我想看下主repo有没有这个问题，结果整下来，嘿，还是报错。

原因尚不清楚，在查询之后我认为是asyncio.run会自动关闭loop，当我尝试直接使用loop的run_until_complete时，更离谱了，Pycharm的exit code是1，也就是说虽然没有报错，但是程序异常终止了，btw？

附上报错信息：

Exception ignored in: <function _ProactorBasePipeTransport.\_\_del\_\_ at 0x0000027122CB6AF0>
Traceback (most recent call last):
&ensp;File "C:\Users\FogFo\.conda\envs\amiya-run\lib\asyncio\proactor_events.py", line 116, in \_\_del\_\_
&ensp;&ensp;self.close()
&ensp;File "C:\Users\FogFo\.conda\envs\amiya-run\lib\asyncio\proactor_events.py", line 108, in close
&ensp;&ensp;self.\_loop.call\_soon(self.\_call\_connection\_lost, None)
&ensp;File "C:\Users\FogFo\.conda\envs\amiya-run\lib\asyncio\base_events.py", line 719, in call_soon
&ensp;&ensp;self.\_check\_closed()
&ensp;File "C:\Users\FogFo\.conda\envs\amiya-run\lib\asyncio\base_events.py", line 508, in \_check\_closed
&ensp;&ensp;raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by FogFoge** [comment]
谢谢@Initial-heart-1 ，重启解决99%的问题

**Comment by Initial-heart-1** [comment]
这不明摆着的 user error
你还好意思交 issue，真有你的啊

**Comment by FogFoge** [comment]
啊对对对

**Comment by Initial-heart-1** [comment]
你啊对对对个屁，我说的不对吗
