### ISSUE TITLE
ctrl + c 强行结束 amiya.py 后，无法返回 cmd/shell 界面

### ISSUE THREAD

**Issue by chaggle** [AmiyaBot/Amiya-Bot#93]
如标题所示，下图是 pycharm 在 windows10 命令行下 ctrl + c  强行结束后，并未返回 cmd 界面。

在 linux 生产环境中，screen 新建一个sh socket ，ctrl + c 后，也无法返回 sh 进行 python amiya.py 的 在启动。

![image](https://user-images.githubusercontent.com/47071009/167330686-c0da562e-063b-42d2-8c32-a76f193730a0.png)
![image](https://user-images.githubusercontent.com/47071009/167330862-dc070312-59a7-4e25-a41c-0db0adedf670.png)

**Comment by Initial-heart-1** [comment]
会等待任务完成后关闭，兔妈这么说过
但是我曾经把它扔在那里不管，然后出现了神奇的报错排查了半小时发现没关掉
建议直接强制关闭
