### ISSUE TITLE
部署了阿米娅之后不能用172.0.0.1配置了

### ISSUE THREAD

**Issue by Tanulav** [AmiyaBot/Amiya-Bot#98]
RT，config文件并没有动过，之前有两个版本忘记开了，今天开了更新之后就无法使用127.0.0.1
显示：127.0.0.1 拒绝了我们的连接请求。

**Comment by Tanulav** [comment]
不过正常使用还是可以的

**Comment by Initial-heart-1** [comment]
亲考虑检查mah

**Comment by Tanulav** [comment]
adapters:
  - http
  - ws
debug: false
enableVerify: true
verifyKey: AmiyaBot
singleMode: false
cacheSize: 4096
adapterSettings:
  http:
    host: 0.0.0.0
    port: 8080
    cors: [ * ]
  ws:
    host: 0.0.0.0
    port: 8060
    reservedSyncId: -1

**Comment by Tanulav** [comment]
用的可执行文件部署的，似乎没有对这里进行过修改

**Comment by Initial-heart-1** [comment]
看一下端口是否被占用，方法百度
8080和8060是热门端口，容易出现端口占用

**Comment by WarfarinBloodanger** [comment]
建议检查后台 Amiya 是否被完整关闭，或者检查一些可能占用 8080 或 8060 端口的程序 / 服务比如 IIS，如果找不到问题或者问题无法解决，那么改变端口配置到别的不常用、非特殊端口上，比如 4080。
